name: Docker Build & Push AppServer Worker to Docker Hub

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  build-and-push:
    name: Build and Push AppServer Worker Image on Local Infrastructure
    runs-on: self-hosted

    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rodrigomicrosiga/smartview-infra-tools-dev:1.0
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}